on:
  workflow_call:
    inputs:
      variables:
        description: JSON list with variables to override others
        type: string
        default: '{}'
        required: false
      universe:
        description: Which universe to get dependencies from
        type: string
        required: false
    secrets:
      DUMMY_SESSION:
      CRANLIKEPWD:
      GH_APP_KEY:
      SLACK_TOKEN:
      BOT_TOKEN:

env: ${{fromJSON(inputs.variables)}}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: lookup
        name: Get info from monorepo
        run: echo "Yay"
        shell: bash
        env: 
          blabla: koekjes
      - id: bla
        name: Get info from monorepo
        uses: actions/checkout@v6
        with: ${{fromJSON(inputs.variables)}}
