on:
  push:
    branches:
      - master
    paths-ignore:
      - '.*'
      - '.*/**'
  workflow_dispatch:
    inputs:
      package:
        description: Which package or commit to build (default is HEAD commit)
        required: false

name: Build package
run-name: ${{ github.event.head_commit.message || format('{0} (rebuild)', inputs.package) }}

jobs:
  prepare:
    if: "!contains(github.event.head_commit.message, 'Deleting packages')"
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.lookup.outputs.repo_name }}
      variables: ${{ toJSON(steps.lookup.outputs) }}
    steps:
      - id: lookup
        name: Get info from monorepo
        run: |
          echo "repo_name=yolo" >> $GITHUB_OUTPUT
          echo "foo=123" >> $GITHUB_OUTPUT
          echo "bar=" >> $GITHUB_OUTPUT
        shell: bash

  build:
    needs: prepare
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - id: lookup
        name: Get info from monorepo
        run: |
          echo "$variables"
        shell: bash
        env: ${{fromJSON(needs.prepare.outputs.variables)}}